In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Providing Data

### Data for Linear Regression

In [10]:
# x=np.array([5,15,25,35,45,55]).reshape((-1,1))
# y=np.array([5,20,14,32,22,38])

### Data for Multiple Linear Regression

In [11]:
x=[[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,35]]
y=[4,5,20,14,32,22,38,43]
x,y=np.array(x),np.array(y)

In [12]:
print(x)
print(y)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]
[ 4  5 20 14 32 22 38 43]


# Create a Model and Fit it

In [13]:
model=LinearRegression()
model.fit(x,y)
model=LinearRegression().fit(x,y)
r_sq=model.score(x,y)
print('coefficient of deterination:',r_sq)

coefficient of deterination: 0.8615939258756775


In [14]:
print('intercept:',model.intercept_)
print('slope:',model.coef_)

intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


# Get Results

In [15]:
new_model=LinearRegression().fit(x,y.reshape((-1,1)))
print('intercept:',new_model.intercept_)
print('slope:',new_model.coef_)

intercept: [5.52257928]
slope: [[0.44706965 0.25502548]]


# Predicted Model

In [16]:
y_pred=model.intercept_+model.coef_*x
print('predictated model:',y_pred,sep='\n')

predictated model:
[[ 5.52257928  5.77760476]
 [ 7.75792752  5.77760476]
 [12.22862401  6.03263024]
 [16.6993205   6.79770668]
 [21.17001699  8.32785957]
 [25.64071348  9.34796149]
 [30.11140997 14.19344564]
 [32.34675821 14.44847112]]
